#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for authorized users of the script:
#
#    1. This script is generated by Gradle. Do not edit it!
#    2. The license of this script is as specified above.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for highlighting syntax.
# shellcheck disable=SC2034
# shellcheck disable=SC2154

while [ -h "$app_path" ]; do
    ls=$(ls -ld "$app_path")
    link=$(expr "$ls" : '.*-> \(.*\)$')
    if expr "$link" : '/.*' > /dev/null; then
        app_path=$link
    else
        app_path=$(dirname "$app_path")/"$link"
    fi
done

APP_HOME=$(dirname "$app_path")
APP_HOME=$(cd "$APP_HOME" > /dev/null && pwd) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    echo "$*"
}

die() {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
CYGWIN*)
    cygwin=true
    ;;
Darwin*)
    darwin=true
    ;;
MINGW*)
    msys=true
    ;;
NONSTOP*)
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ]; then
    if [ -x "$JAVA_HOME/jre/sh/java" ]; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ]; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "false" ] && [ "$msys" = "false" ] && [ "$darwin" = "false" ] && [ "$nonstop" = "false" ]; then
    MAX_FD_LIMIT=$(ulimit -H -n)
    if [ $? -eq 0 ]; then
        if [ "$MAX_FD" = "maximum" ] || [ "$MAX_FD" = "max" ]; then
            MAX_FD=$MAX_FD_LIMIT
        fi
        ulimit -n "$MAX_FD"
        if [ $? -ne 0 ]; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Cygwin, switch paths to Windows format before running java
if [ "$cygwin" = "true" ]; then
    APP_HOME=$(cygpath --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=$(cygpath --mixed /)
    # Remove a trailing slash.
    ROOTDIRS=${ROOTDIRSRAW%/}
    # This is a bit of a hack to handle transitive dependencies of gradle-wrapper.jar
    # (i.e. those jars that are in the same directory as gradle-wrapper.jar)
    # In practice there are currently none.
    # We use a pattern to avoid including non-jar files.
    # shellcheck disable=SC2154
    for i in "$APP_HOME"/gradle/wrapper/*.jar; do
        if [ -f "$i" ]; then
            CLASSPATH=$CLASSPATH:$(cygpath --path --mixed "$i")
        fi
    done

    # Set appropriate environment variables for child processes.
    # (Internal Gradle mechanism for when it is running as a wrapper)
    # shellcheck disable=SC2154
    # shellcheck disable=SC2030
    eval "export JAVA_OPTS=\"\$JAVA_OPTS -Dorg.gradle.native.dir=\\\"\$ROOTDIRS\\\"\""
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when a command fails.
set -e

# Execute Gradle
exec "$JAVACMD" "$@"
